{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7708a87c",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-09-13T05:32:29.139396Z",
     "iopub.status.busy": "2022-09-13T05:32:29.136893Z",
     "iopub.status.idle": "2022-09-13T05:33:12.879429Z",
     "shell.execute_reply": "2022-09-13T05:33:12.877530Z"
    },
    "papermill": {
     "duration": 43.752184,
     "end_time": "2022-09-13T05:33:12.883544",
     "exception": false,
     "start_time": "2022-09-13T05:32:29.131360",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "#Reading the \"previous_app.csv\" into the dataframe prev_data\n",
    "prev_data <- read.csv(file = '../input/credit-analysis/previous_app.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cb67ba12",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-09-13T05:33:12.918746Z",
     "iopub.status.busy": "2022-09-13T05:33:12.890277Z",
     "iopub.status.idle": "2022-09-13T05:33:28.085755Z",
     "shell.execute_reply": "2022-09-13T05:33:28.083925Z"
    },
    "papermill": {
     "duration": 15.203296,
     "end_time": "2022-09-13T05:33:28.089621",
     "exception": false,
     "start_time": "2022-09-13T05:33:12.886325",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "#Reading the \"current_app.csv\" into the dataframe prev_data\n",
    "curr_data <- read.csv(file = '../input/credit-analysis/current_app.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7f9900cb",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-09-13T05:33:28.097754Z",
     "iopub.status.busy": "2022-09-13T05:33:28.096208Z",
     "iopub.status.idle": "2022-09-13T05:33:28.136338Z",
     "shell.execute_reply": "2022-09-13T05:33:28.134654Z"
    },
    "papermill": {
     "duration": 0.047977,
     "end_time": "2022-09-13T05:33:28.139879",
     "exception": false,
     "start_time": "2022-09-13T05:33:28.091902",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table class=\"dataframe\">\n",
       "<caption>A data.frame: 5 × 37</caption>\n",
       "<thead>\n",
       "\t<tr><th></th><th scope=col>SK_ID_PREV</th><th scope=col>SK_ID_CURR</th><th scope=col>NAME_CONTRACT_TYPE</th><th scope=col>AMT_ANNUITY</th><th scope=col>AMT_APPLICATION</th><th scope=col>AMT_CREDIT</th><th scope=col>AMT_DOWN_PAYMENT</th><th scope=col>AMT_GOODS_PRICE</th><th scope=col>WEEKDAY_APPR_PROCESS_START</th><th scope=col>HOUR_APPR_PROCESS_START</th><th scope=col>⋯</th><th scope=col>NAME_SELLER_INDUSTRY</th><th scope=col>CNT_PAYMENT</th><th scope=col>NAME_YIELD_GROUP</th><th scope=col>PRODUCT_COMBINATION</th><th scope=col>DAYS_FIRST_DRAWING</th><th scope=col>DAYS_FIRST_DUE</th><th scope=col>DAYS_LAST_DUE_1ST_VERSION</th><th scope=col>DAYS_LAST_DUE</th><th scope=col>DAYS_TERMINATION</th><th scope=col>NFLAG_INSURED_ON_APPROVAL</th></tr>\n",
       "\t<tr><th></th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>⋯</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "\t<tr><th scope=row>1</th><td>2030495</td><td>271877</td><td>Consumer loans</td><td> 1730.43</td><td> 17145</td><td> 17145.0</td><td> 0</td><td> 17145</td><td>SATURDAY</td><td>15</td><td>⋯</td><td>Connectivity</td><td>12</td><td>middle    </td><td>POS mobile with interest</td><td>365243</td><td> -42</td><td> 300</td><td>   -42</td><td>   -37</td><td> 0</td></tr>\n",
       "\t<tr><th scope=row>2</th><td>2802425</td><td>108129</td><td>Cash loans    </td><td>25188.62</td><td>607500</td><td>679671.0</td><td>NA</td><td>607500</td><td>THURSDAY</td><td>11</td><td>⋯</td><td>XNA         </td><td>36</td><td>low_action</td><td>Cash X-Sell: low        </td><td>365243</td><td>-134</td><td> 916</td><td>365243</td><td>365243</td><td> 1</td></tr>\n",
       "\t<tr><th scope=row>3</th><td>2523466</td><td>122040</td><td>Cash loans    </td><td>15060.74</td><td>112500</td><td>136444.5</td><td>NA</td><td>112500</td><td>TUESDAY </td><td>11</td><td>⋯</td><td>XNA         </td><td>12</td><td>high      </td><td>Cash X-Sell: high       </td><td>365243</td><td>-271</td><td>  59</td><td>365243</td><td>365243</td><td> 1</td></tr>\n",
       "\t<tr><th scope=row>4</th><td>2819243</td><td>176158</td><td>Cash loans    </td><td>47041.33</td><td>450000</td><td>470790.0</td><td>NA</td><td>450000</td><td>MONDAY  </td><td> 7</td><td>⋯</td><td>XNA         </td><td>12</td><td>middle    </td><td>Cash X-Sell: middle     </td><td>365243</td><td>-482</td><td>-152</td><td>  -182</td><td>  -177</td><td> 1</td></tr>\n",
       "\t<tr><th scope=row>5</th><td>1784265</td><td>202054</td><td>Cash loans    </td><td>31924.40</td><td>337500</td><td>404055.0</td><td>NA</td><td>337500</td><td>THURSDAY</td><td> 9</td><td>⋯</td><td>XNA         </td><td>24</td><td>high      </td><td>Cash Street: high       </td><td>    NA</td><td>  NA</td><td>  NA</td><td>    NA</td><td>    NA</td><td>NA</td></tr>\n",
       "</tbody>\n",
       "</table>\n"
      ],
      "text/latex": [
       "A data.frame: 5 × 37\n",
       "\\begin{tabular}{r|lllllllllllllllllllll}\n",
       "  & SK\\_ID\\_PREV & SK\\_ID\\_CURR & NAME\\_CONTRACT\\_TYPE & AMT\\_ANNUITY & AMT\\_APPLICATION & AMT\\_CREDIT & AMT\\_DOWN\\_PAYMENT & AMT\\_GOODS\\_PRICE & WEEKDAY\\_APPR\\_PROCESS\\_START & HOUR\\_APPR\\_PROCESS\\_START & ⋯ & NAME\\_SELLER\\_INDUSTRY & CNT\\_PAYMENT & NAME\\_YIELD\\_GROUP & PRODUCT\\_COMBINATION & DAYS\\_FIRST\\_DRAWING & DAYS\\_FIRST\\_DUE & DAYS\\_LAST\\_DUE\\_1ST\\_VERSION & DAYS\\_LAST\\_DUE & DAYS\\_TERMINATION & NFLAG\\_INSURED\\_ON\\_APPROVAL\\\\\n",
       "  & <int> & <int> & <chr> & <dbl> & <dbl> & <dbl> & <dbl> & <dbl> & <chr> & <int> & ⋯ & <chr> & <dbl> & <chr> & <chr> & <dbl> & <dbl> & <dbl> & <dbl> & <dbl> & <dbl>\\\\\n",
       "\\hline\n",
       "\t1 & 2030495 & 271877 & Consumer loans &  1730.43 &  17145 &  17145.0 &  0 &  17145 & SATURDAY & 15 & ⋯ & Connectivity & 12 & middle     & POS mobile with interest & 365243 &  -42 &  300 &    -42 &    -37 &  0\\\\\n",
       "\t2 & 2802425 & 108129 & Cash loans     & 25188.62 & 607500 & 679671.0 & NA & 607500 & THURSDAY & 11 & ⋯ & XNA          & 36 & low\\_action & Cash X-Sell: low         & 365243 & -134 &  916 & 365243 & 365243 &  1\\\\\n",
       "\t3 & 2523466 & 122040 & Cash loans     & 15060.74 & 112500 & 136444.5 & NA & 112500 & TUESDAY  & 11 & ⋯ & XNA          & 12 & high       & Cash X-Sell: high        & 365243 & -271 &   59 & 365243 & 365243 &  1\\\\\n",
       "\t4 & 2819243 & 176158 & Cash loans     & 47041.33 & 450000 & 470790.0 & NA & 450000 & MONDAY   &  7 & ⋯ & XNA          & 12 & middle     & Cash X-Sell: middle      & 365243 & -482 & -152 &   -182 &   -177 &  1\\\\\n",
       "\t5 & 1784265 & 202054 & Cash loans     & 31924.40 & 337500 & 404055.0 & NA & 337500 & THURSDAY &  9 & ⋯ & XNA          & 24 & high       & Cash Street: high        &     NA &   NA &   NA &     NA &     NA & NA\\\\\n",
       "\\end{tabular}\n"
      ],
      "text/markdown": [
       "\n",
       "A data.frame: 5 × 37\n",
       "\n",
       "| <!--/--> | SK_ID_PREV &lt;int&gt; | SK_ID_CURR &lt;int&gt; | NAME_CONTRACT_TYPE &lt;chr&gt; | AMT_ANNUITY &lt;dbl&gt; | AMT_APPLICATION &lt;dbl&gt; | AMT_CREDIT &lt;dbl&gt; | AMT_DOWN_PAYMENT &lt;dbl&gt; | AMT_GOODS_PRICE &lt;dbl&gt; | WEEKDAY_APPR_PROCESS_START &lt;chr&gt; | HOUR_APPR_PROCESS_START &lt;int&gt; | ⋯ ⋯ | NAME_SELLER_INDUSTRY &lt;chr&gt; | CNT_PAYMENT &lt;dbl&gt; | NAME_YIELD_GROUP &lt;chr&gt; | PRODUCT_COMBINATION &lt;chr&gt; | DAYS_FIRST_DRAWING &lt;dbl&gt; | DAYS_FIRST_DUE &lt;dbl&gt; | DAYS_LAST_DUE_1ST_VERSION &lt;dbl&gt; | DAYS_LAST_DUE &lt;dbl&gt; | DAYS_TERMINATION &lt;dbl&gt; | NFLAG_INSURED_ON_APPROVAL &lt;dbl&gt; |\n",
       "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n",
       "| 1 | 2030495 | 271877 | Consumer loans |  1730.43 |  17145 |  17145.0 |  0 |  17145 | SATURDAY | 15 | ⋯ | Connectivity | 12 | middle     | POS mobile with interest | 365243 |  -42 |  300 |    -42 |    -37 |  0 |\n",
       "| 2 | 2802425 | 108129 | Cash loans     | 25188.62 | 607500 | 679671.0 | NA | 607500 | THURSDAY | 11 | ⋯ | XNA          | 36 | low_action | Cash X-Sell: low         | 365243 | -134 |  916 | 365243 | 365243 |  1 |\n",
       "| 3 | 2523466 | 122040 | Cash loans     | 15060.74 | 112500 | 136444.5 | NA | 112500 | TUESDAY  | 11 | ⋯ | XNA          | 12 | high       | Cash X-Sell: high        | 365243 | -271 |   59 | 365243 | 365243 |  1 |\n",
       "| 4 | 2819243 | 176158 | Cash loans     | 47041.33 | 450000 | 470790.0 | NA | 450000 | MONDAY   |  7 | ⋯ | XNA          | 12 | middle     | Cash X-Sell: middle      | 365243 | -482 | -152 |   -182 |   -177 |  1 |\n",
       "| 5 | 1784265 | 202054 | Cash loans     | 31924.40 | 337500 | 404055.0 | NA | 337500 | THURSDAY |  9 | ⋯ | XNA          | 24 | high       | Cash Street: high        |     NA |   NA |   NA |     NA |     NA | NA |\n",
       "\n"
      ],
      "text/plain": [
       "  SK_ID_PREV SK_ID_CURR NAME_CONTRACT_TYPE AMT_ANNUITY AMT_APPLICATION\n",
       "1 2030495    271877     Consumer loans      1730.43     17145         \n",
       "2 2802425    108129     Cash loans         25188.62    607500         \n",
       "3 2523466    122040     Cash loans         15060.74    112500         \n",
       "4 2819243    176158     Cash loans         47041.33    450000         \n",
       "5 1784265    202054     Cash loans         31924.40    337500         \n",
       "  AMT_CREDIT AMT_DOWN_PAYMENT AMT_GOODS_PRICE WEEKDAY_APPR_PROCESS_START\n",
       "1  17145.0    0                17145          SATURDAY                  \n",
       "2 679671.0   NA               607500          THURSDAY                  \n",
       "3 136444.5   NA               112500          TUESDAY                   \n",
       "4 470790.0   NA               450000          MONDAY                    \n",
       "5 404055.0   NA               337500          THURSDAY                  \n",
       "  HOUR_APPR_PROCESS_START ⋯ NAME_SELLER_INDUSTRY CNT_PAYMENT NAME_YIELD_GROUP\n",
       "1 15                      ⋯ Connectivity         12          middle          \n",
       "2 11                      ⋯ XNA                  36          low_action      \n",
       "3 11                      ⋯ XNA                  12          high            \n",
       "4  7                      ⋯ XNA                  12          middle          \n",
       "5  9                      ⋯ XNA                  24          high            \n",
       "  PRODUCT_COMBINATION      DAYS_FIRST_DRAWING DAYS_FIRST_DUE\n",
       "1 POS mobile with interest 365243              -42          \n",
       "2 Cash X-Sell: low         365243             -134          \n",
       "3 Cash X-Sell: high        365243             -271          \n",
       "4 Cash X-Sell: middle      365243             -482          \n",
       "5 Cash Street: high            NA               NA          \n",
       "  DAYS_LAST_DUE_1ST_VERSION DAYS_LAST_DUE DAYS_TERMINATION\n",
       "1  300                         -42           -37          \n",
       "2  916                      365243        365243          \n",
       "3   59                      365243        365243          \n",
       "4 -152                        -182          -177          \n",
       "5   NA                          NA            NA          \n",
       "  NFLAG_INSURED_ON_APPROVAL\n",
       "1  0                       \n",
       "2  1                       \n",
       "3  1                       \n",
       "4  1                       \n",
       "5 NA                       "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#printing the head of the dataframe to view the data available\n",
    "head(prev_data,n=5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ac00d719",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-09-13T05:33:28.151714Z",
     "iopub.status.busy": "2022-09-13T05:33:28.149997Z",
     "iopub.status.idle": "2022-09-13T05:33:28.910294Z",
     "shell.execute_reply": "2022-09-13T05:33:28.908655Z"
    },
    "papermill": {
     "duration": 0.770458,
     "end_time": "2022-09-13T05:33:28.912975",
     "exception": false,
     "start_time": "2022-09-13T05:33:28.142517",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".dl-inline {width: auto; margin:0; padding: 0}\n",
       ".dl-inline>dt, .dl-inline>dd {float: none; width: auto; display: inline-block}\n",
       ".dl-inline>dt::after {content: \":\\0020\"; padding-right: .5ex}\n",
       ".dl-inline>dt:not(:first-of-type) {padding-left: .5ex}\n",
       "</style><dl class=dl-inline><dt>SK_ID_PREV</dt><dd>0</dd><dt>SK_ID_CURR</dt><dd>0</dd><dt>NAME_CONTRACT_TYPE</dt><dd>0</dd><dt>AMT_ANNUITY</dt><dd>372235</dd><dt>AMT_APPLICATION</dt><dd>0</dd><dt>AMT_CREDIT</dt><dd>1</dd><dt>AMT_DOWN_PAYMENT</dt><dd>895844</dd><dt>AMT_GOODS_PRICE</dt><dd>385515</dd><dt>WEEKDAY_APPR_PROCESS_START</dt><dd>0</dd><dt>HOUR_APPR_PROCESS_START</dt><dd>0</dd><dt>FLAG_LAST_APPL_PER_CONTRACT</dt><dd>0</dd><dt>NFLAG_LAST_APPL_IN_DAY</dt><dd>0</dd><dt>RATE_DOWN_PAYMENT</dt><dd>895844</dd><dt>RATE_INTEREST_PRIMARY</dt><dd>1664263</dd><dt>RATE_INTEREST_PRIVILEGED</dt><dd>1664263</dd><dt>NAME_CASH_LOAN_PURPOSE</dt><dd>0</dd><dt>NAME_CONTRACT_STATUS</dt><dd>0</dd><dt>DAYS_DECISION</dt><dd>0</dd><dt>NAME_PAYMENT_TYPE</dt><dd>0</dd><dt>CODE_REJECT_REASON</dt><dd>0</dd><dt>NAME_TYPE_SUITE</dt><dd>0</dd><dt>NAME_CLIENT_TYPE</dt><dd>0</dd><dt>NAME_GOODS_CATEGORY</dt><dd>0</dd><dt>NAME_PORTFOLIO</dt><dd>0</dd><dt>NAME_PRODUCT_TYPE</dt><dd>0</dd><dt>CHANNEL_TYPE</dt><dd>0</dd><dt>SELLERPLACE_AREA</dt><dd>0</dd><dt>NAME_SELLER_INDUSTRY</dt><dd>0</dd><dt>CNT_PAYMENT</dt><dd>372230</dd><dt>NAME_YIELD_GROUP</dt><dd>0</dd><dt>PRODUCT_COMBINATION</dt><dd>0</dd><dt>DAYS_FIRST_DRAWING</dt><dd>673065</dd><dt>DAYS_FIRST_DUE</dt><dd>673065</dd><dt>DAYS_LAST_DUE_1ST_VERSION</dt><dd>673065</dd><dt>DAYS_LAST_DUE</dt><dd>673065</dd><dt>DAYS_TERMINATION</dt><dd>673065</dd><dt>NFLAG_INSURED_ON_APPROVAL</dt><dd>673065</dd></dl>\n"
      ],
      "text/latex": [
       "\\begin{description*}\n",
       "\\item[SK\\textbackslash{}\\_ID\\textbackslash{}\\_PREV] 0\n",
       "\\item[SK\\textbackslash{}\\_ID\\textbackslash{}\\_CURR] 0\n",
       "\\item[NAME\\textbackslash{}\\_CONTRACT\\textbackslash{}\\_TYPE] 0\n",
       "\\item[AMT\\textbackslash{}\\_ANNUITY] 372235\n",
       "\\item[AMT\\textbackslash{}\\_APPLICATION] 0\n",
       "\\item[AMT\\textbackslash{}\\_CREDIT] 1\n",
       "\\item[AMT\\textbackslash{}\\_DOWN\\textbackslash{}\\_PAYMENT] 895844\n",
       "\\item[AMT\\textbackslash{}\\_GOODS\\textbackslash{}\\_PRICE] 385515\n",
       "\\item[WEEKDAY\\textbackslash{}\\_APPR\\textbackslash{}\\_PROCESS\\textbackslash{}\\_START] 0\n",
       "\\item[HOUR\\textbackslash{}\\_APPR\\textbackslash{}\\_PROCESS\\textbackslash{}\\_START] 0\n",
       "\\item[FLAG\\textbackslash{}\\_LAST\\textbackslash{}\\_APPL\\textbackslash{}\\_PER\\textbackslash{}\\_CONTRACT] 0\n",
       "\\item[NFLAG\\textbackslash{}\\_LAST\\textbackslash{}\\_APPL\\textbackslash{}\\_IN\\textbackslash{}\\_DAY] 0\n",
       "\\item[RATE\\textbackslash{}\\_DOWN\\textbackslash{}\\_PAYMENT] 895844\n",
       "\\item[RATE\\textbackslash{}\\_INTEREST\\textbackslash{}\\_PRIMARY] 1664263\n",
       "\\item[RATE\\textbackslash{}\\_INTEREST\\textbackslash{}\\_PRIVILEGED] 1664263\n",
       "\\item[NAME\\textbackslash{}\\_CASH\\textbackslash{}\\_LOAN\\textbackslash{}\\_PURPOSE] 0\n",
       "\\item[NAME\\textbackslash{}\\_CONTRACT\\textbackslash{}\\_STATUS] 0\n",
       "\\item[DAYS\\textbackslash{}\\_DECISION] 0\n",
       "\\item[NAME\\textbackslash{}\\_PAYMENT\\textbackslash{}\\_TYPE] 0\n",
       "\\item[CODE\\textbackslash{}\\_REJECT\\textbackslash{}\\_REASON] 0\n",
       "\\item[NAME\\textbackslash{}\\_TYPE\\textbackslash{}\\_SUITE] 0\n",
       "\\item[NAME\\textbackslash{}\\_CLIENT\\textbackslash{}\\_TYPE] 0\n",
       "\\item[NAME\\textbackslash{}\\_GOODS\\textbackslash{}\\_CATEGORY] 0\n",
       "\\item[NAME\\textbackslash{}\\_PORTFOLIO] 0\n",
       "\\item[NAME\\textbackslash{}\\_PRODUCT\\textbackslash{}\\_TYPE] 0\n",
       "\\item[CHANNEL\\textbackslash{}\\_TYPE] 0\n",
       "\\item[SELLERPLACE\\textbackslash{}\\_AREA] 0\n",
       "\\item[NAME\\textbackslash{}\\_SELLER\\textbackslash{}\\_INDUSTRY] 0\n",
       "\\item[CNT\\textbackslash{}\\_PAYMENT] 372230\n",
       "\\item[NAME\\textbackslash{}\\_YIELD\\textbackslash{}\\_GROUP] 0\n",
       "\\item[PRODUCT\\textbackslash{}\\_COMBINATION] 0\n",
       "\\item[DAYS\\textbackslash{}\\_FIRST\\textbackslash{}\\_DRAWING] 673065\n",
       "\\item[DAYS\\textbackslash{}\\_FIRST\\textbackslash{}\\_DUE] 673065\n",
       "\\item[DAYS\\textbackslash{}\\_LAST\\textbackslash{}\\_DUE\\textbackslash{}\\_1ST\\textbackslash{}\\_VERSION] 673065\n",
       "\\item[DAYS\\textbackslash{}\\_LAST\\textbackslash{}\\_DUE] 673065\n",
       "\\item[DAYS\\textbackslash{}\\_TERMINATION] 673065\n",
       "\\item[NFLAG\\textbackslash{}\\_INSURED\\textbackslash{}\\_ON\\textbackslash{}\\_APPROVAL] 673065\n",
       "\\end{description*}\n"
      ],
      "text/markdown": [
       "SK_ID_PREV\n",
       ":   0SK_ID_CURR\n",
       ":   0NAME_CONTRACT_TYPE\n",
       ":   0AMT_ANNUITY\n",
       ":   372235AMT_APPLICATION\n",
       ":   0AMT_CREDIT\n",
       ":   1AMT_DOWN_PAYMENT\n",
       ":   895844AMT_GOODS_PRICE\n",
       ":   385515WEEKDAY_APPR_PROCESS_START\n",
       ":   0HOUR_APPR_PROCESS_START\n",
       ":   0FLAG_LAST_APPL_PER_CONTRACT\n",
       ":   0NFLAG_LAST_APPL_IN_DAY\n",
       ":   0RATE_DOWN_PAYMENT\n",
       ":   895844RATE_INTEREST_PRIMARY\n",
       ":   1664263RATE_INTEREST_PRIVILEGED\n",
       ":   1664263NAME_CASH_LOAN_PURPOSE\n",
       ":   0NAME_CONTRACT_STATUS\n",
       ":   0DAYS_DECISION\n",
       ":   0NAME_PAYMENT_TYPE\n",
       ":   0CODE_REJECT_REASON\n",
       ":   0NAME_TYPE_SUITE\n",
       ":   0NAME_CLIENT_TYPE\n",
       ":   0NAME_GOODS_CATEGORY\n",
       ":   0NAME_PORTFOLIO\n",
       ":   0NAME_PRODUCT_TYPE\n",
       ":   0CHANNEL_TYPE\n",
       ":   0SELLERPLACE_AREA\n",
       ":   0NAME_SELLER_INDUSTRY\n",
       ":   0CNT_PAYMENT\n",
       ":   372230NAME_YIELD_GROUP\n",
       ":   0PRODUCT_COMBINATION\n",
       ":   0DAYS_FIRST_DRAWING\n",
       ":   673065DAYS_FIRST_DUE\n",
       ":   673065DAYS_LAST_DUE_1ST_VERSION\n",
       ":   673065DAYS_LAST_DUE\n",
       ":   673065DAYS_TERMINATION\n",
       ":   673065NFLAG_INSURED_ON_APPROVAL\n",
       ":   673065\n",
       "\n"
      ],
      "text/plain": [
       "                 SK_ID_PREV                  SK_ID_CURR \n",
       "                          0                           0 \n",
       "         NAME_CONTRACT_TYPE                 AMT_ANNUITY \n",
       "                          0                      372235 \n",
       "            AMT_APPLICATION                  AMT_CREDIT \n",
       "                          0                           1 \n",
       "           AMT_DOWN_PAYMENT             AMT_GOODS_PRICE \n",
       "                     895844                      385515 \n",
       " WEEKDAY_APPR_PROCESS_START     HOUR_APPR_PROCESS_START \n",
       "                          0                           0 \n",
       "FLAG_LAST_APPL_PER_CONTRACT      NFLAG_LAST_APPL_IN_DAY \n",
       "                          0                           0 \n",
       "          RATE_DOWN_PAYMENT       RATE_INTEREST_PRIMARY \n",
       "                     895844                     1664263 \n",
       "   RATE_INTEREST_PRIVILEGED      NAME_CASH_LOAN_PURPOSE \n",
       "                    1664263                           0 \n",
       "       NAME_CONTRACT_STATUS               DAYS_DECISION \n",
       "                          0                           0 \n",
       "          NAME_PAYMENT_TYPE          CODE_REJECT_REASON \n",
       "                          0                           0 \n",
       "            NAME_TYPE_SUITE            NAME_CLIENT_TYPE \n",
       "                          0                           0 \n",
       "        NAME_GOODS_CATEGORY              NAME_PORTFOLIO \n",
       "                          0                           0 \n",
       "          NAME_PRODUCT_TYPE                CHANNEL_TYPE \n",
       "                          0                           0 \n",
       "           SELLERPLACE_AREA        NAME_SELLER_INDUSTRY \n",
       "                          0                           0 \n",
       "                CNT_PAYMENT            NAME_YIELD_GROUP \n",
       "                     372230                           0 \n",
       "        PRODUCT_COMBINATION          DAYS_FIRST_DRAWING \n",
       "                          0                      673065 \n",
       "             DAYS_FIRST_DUE   DAYS_LAST_DUE_1ST_VERSION \n",
       "                     673065                      673065 \n",
       "              DAYS_LAST_DUE            DAYS_TERMINATION \n",
       "                     673065                      673065 \n",
       "  NFLAG_INSURED_ON_APPROVAL \n",
       "                     673065 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#finding sum of null values in every column\n",
    "colSums(is.na(prev_data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c1b496e9",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-09-13T05:33:28.923213Z",
     "iopub.status.busy": "2022-09-13T05:33:28.921202Z",
     "iopub.status.idle": "2022-09-13T05:33:29.121571Z",
     "shell.execute_reply": "2022-09-13T05:33:29.118678Z"
    },
    "papermill": {
     "duration": 0.20914,
     "end_time": "2022-09-13T05:33:29.125026",
     "exception": false,
     "start_time": "2022-09-13T05:33:28.915886",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".dl-inline {width: auto; margin:0; padding: 0}\n",
       ".dl-inline>dt, .dl-inline>dd {float: none; width: auto; display: inline-block}\n",
       ".dl-inline>dt::after {content: \":\\0020\"; padding-right: .5ex}\n",
       ".dl-inline>dt:not(:first-of-type) {padding-left: .5ex}\n",
       "</style><dl class=dl-inline><dt>SK_ID_CURR</dt><dd>0</dd><dt>TARGET</dt><dd>0</dd><dt>NAME_CONTRACT_TYPE</dt><dd>0</dd><dt>CODE_GENDER</dt><dd>0</dd><dt>FLAG_OWN_CAR</dt><dd>0</dd><dt>FLAG_OWN_REALTY</dt><dd>0</dd><dt>CNT_CHILDREN</dt><dd>0</dd><dt>AMT_INCOME_TOTAL</dt><dd>0</dd><dt>AMT_CREDIT</dt><dd>0</dd><dt>AMT_ANNUITY</dt><dd>12</dd><dt>AMT_GOODS_PRICE</dt><dd>278</dd><dt>NAME_TYPE_SUITE</dt><dd>0</dd><dt>NAME_INCOME_TYPE</dt><dd>0</dd><dt>NAME_EDUCATION_TYPE</dt><dd>0</dd><dt>NAME_FAMILY_STATUS</dt><dd>0</dd><dt>NAME_HOUSING_TYPE</dt><dd>0</dd><dt>REGION_POPULATION_RELATIVE</dt><dd>0</dd><dt>DAYS_BIRTH</dt><dd>0</dd><dt>DAYS_EMPLOYED</dt><dd>0</dd><dt>DAYS_REGISTRATION</dt><dd>0</dd><dt>DAYS_ID_PUBLISH</dt><dd>0</dd><dt>OWN_CAR_AGE</dt><dd>202929</dd><dt>FLAG_MOBIL</dt><dd>0</dd><dt>FLAG_EMP_PHONE</dt><dd>0</dd><dt>FLAG_WORK_PHONE</dt><dd>0</dd><dt>FLAG_CONT_MOBILE</dt><dd>0</dd><dt>FLAG_PHONE</dt><dd>0</dd><dt>FLAG_EMAIL</dt><dd>0</dd><dt>OCCUPATION_TYPE</dt><dd>0</dd><dt>CNT_FAM_MEMBERS</dt><dd>2</dd><dt>REGION_RATING_CLIENT</dt><dd>0</dd><dt>REGION_RATING_CLIENT_W_CITY</dt><dd>0</dd><dt>WEEKDAY_APPR_PROCESS_START</dt><dd>0</dd><dt>HOUR_APPR_PROCESS_START</dt><dd>0</dd><dt>REG_REGION_NOT_LIVE_REGION</dt><dd>0</dd><dt>REG_REGION_NOT_WORK_REGION</dt><dd>0</dd><dt>LIVE_REGION_NOT_WORK_REGION</dt><dd>0</dd><dt>REG_CITY_NOT_LIVE_CITY</dt><dd>0</dd><dt>REG_CITY_NOT_WORK_CITY</dt><dd>0</dd><dt>LIVE_CITY_NOT_WORK_CITY</dt><dd>0</dd><dt>ORGANIZATION_TYPE</dt><dd>0</dd><dt>EXT_SOURCE_1</dt><dd>173378</dd><dt>EXT_SOURCE_2</dt><dd>660</dd><dt>EXT_SOURCE_3</dt><dd>60965</dd><dt>APARTMENTS_AVG</dt><dd>156061</dd><dt>BASEMENTAREA_AVG</dt><dd>179943</dd><dt>YEARS_BEGINEXPLUATATION_AVG</dt><dd>150007</dd><dt>YEARS_BUILD_AVG</dt><dd>204488</dd><dt>COMMONAREA_AVG</dt><dd>214865</dd><dt>ELEVATORS_AVG</dt><dd>163891</dd><dt>ENTRANCES_AVG</dt><dd>154828</dd><dt>FLOORSMAX_AVG</dt><dd>153020</dd><dt>FLOORSMIN_AVG</dt><dd>208642</dd><dt>LANDAREA_AVG</dt><dd>182590</dd><dt>LIVINGAPARTMENTS_AVG</dt><dd>210199</dd><dt>LIVINGAREA_AVG</dt><dd>154350</dd><dt>NONLIVINGAPARTMENTS_AVG</dt><dd>213514</dd><dt>NONLIVINGAREA_AVG</dt><dd>169682</dd><dt>APARTMENTS_MODE</dt><dd>156061</dd><dt>BASEMENTAREA_MODE</dt><dd>179943</dd><dt>YEARS_BEGINEXPLUATATION_MODE</dt><dd>150007</dd><dt>YEARS_BUILD_MODE</dt><dd>204488</dd><dt>COMMONAREA_MODE</dt><dd>214865</dd><dt>ELEVATORS_MODE</dt><dd>163891</dd><dt>ENTRANCES_MODE</dt><dd>154828</dd><dt>FLOORSMAX_MODE</dt><dd>153020</dd><dt>FLOORSMIN_MODE</dt><dd>208642</dd><dt>LANDAREA_MODE</dt><dd>182590</dd><dt>LIVINGAPARTMENTS_MODE</dt><dd>210199</dd><dt>LIVINGAREA_MODE</dt><dd>154350</dd><dt>NONLIVINGAPARTMENTS_MODE</dt><dd>213514</dd><dt>NONLIVINGAREA_MODE</dt><dd>169682</dd><dt>APARTMENTS_MEDI</dt><dd>156061</dd><dt>BASEMENTAREA_MEDI</dt><dd>179943</dd><dt>YEARS_BEGINEXPLUATATION_MEDI</dt><dd>150007</dd><dt>YEARS_BUILD_MEDI</dt><dd>204488</dd><dt>COMMONAREA_MEDI</dt><dd>214865</dd><dt>ELEVATORS_MEDI</dt><dd>163891</dd><dt>ENTRANCES_MEDI</dt><dd>154828</dd><dt>FLOORSMAX_MEDI</dt><dd>153020</dd><dt>FLOORSMIN_MEDI</dt><dd>208642</dd><dt>LANDAREA_MEDI</dt><dd>182590</dd><dt>LIVINGAPARTMENTS_MEDI</dt><dd>210199</dd><dt>LIVINGAREA_MEDI</dt><dd>154350</dd><dt>NONLIVINGAPARTMENTS_MEDI</dt><dd>213514</dd><dt>NONLIVINGAREA_MEDI</dt><dd>169682</dd><dt>FONDKAPREMONT_MODE</dt><dd>0</dd><dt>HOUSETYPE_MODE</dt><dd>0</dd><dt>TOTALAREA_MODE</dt><dd>148431</dd><dt>WALLSMATERIAL_MODE</dt><dd>0</dd><dt>EMERGENCYSTATE_MODE</dt><dd>0</dd><dt>OBS_30_CNT_SOCIAL_CIRCLE</dt><dd>1021</dd><dt>DEF_30_CNT_SOCIAL_CIRCLE</dt><dd>1021</dd><dt>OBS_60_CNT_SOCIAL_CIRCLE</dt><dd>1021</dd><dt>DEF_60_CNT_SOCIAL_CIRCLE</dt><dd>1021</dd><dt>DAYS_LAST_PHONE_CHANGE</dt><dd>1</dd><dt>FLAG_DOCUMENT_2</dt><dd>0</dd><dt>FLAG_DOCUMENT_3</dt><dd>0</dd><dt>FLAG_DOCUMENT_4</dt><dd>0</dd><dt>FLAG_DOCUMENT_5</dt><dd>0</dd><dt>FLAG_DOCUMENT_6</dt><dd>0</dd><dt>FLAG_DOCUMENT_7</dt><dd>0</dd><dt>FLAG_DOCUMENT_8</dt><dd>0</dd><dt>FLAG_DOCUMENT_9</dt><dd>0</dd><dt>FLAG_DOCUMENT_10</dt><dd>0</dd><dt>FLAG_DOCUMENT_11</dt><dd>0</dd><dt>FLAG_DOCUMENT_12</dt><dd>0</dd><dt>FLAG_DOCUMENT_13</dt><dd>0</dd><dt>FLAG_DOCUMENT_14</dt><dd>0</dd><dt>FLAG_DOCUMENT_15</dt><dd>0</dd><dt>FLAG_DOCUMENT_16</dt><dd>0</dd><dt>FLAG_DOCUMENT_17</dt><dd>0</dd><dt>FLAG_DOCUMENT_18</dt><dd>0</dd><dt>FLAG_DOCUMENT_19</dt><dd>0</dd><dt>FLAG_DOCUMENT_20</dt><dd>0</dd><dt>FLAG_DOCUMENT_21</dt><dd>0</dd><dt>AMT_REQ_CREDIT_BUREAU_HOUR</dt><dd>41519</dd><dt>AMT_REQ_CREDIT_BUREAU_DAY</dt><dd>41519</dd><dt>AMT_REQ_CREDIT_BUREAU_WEEK</dt><dd>41519</dd><dt>AMT_REQ_CREDIT_BUREAU_MON</dt><dd>41519</dd><dt>AMT_REQ_CREDIT_BUREAU_QRT</dt><dd>41519</dd><dt>AMT_REQ_CREDIT_BUREAU_YEAR</dt><dd>41519</dd></dl>\n"
      ],
      "text/latex": [
       "\\begin{description*}\n",
       "\\item[SK\\textbackslash{}\\_ID\\textbackslash{}\\_CURR] 0\n",
       "\\item[TARGET] 0\n",
       "\\item[NAME\\textbackslash{}\\_CONTRACT\\textbackslash{}\\_TYPE] 0\n",
       "\\item[CODE\\textbackslash{}\\_GENDER] 0\n",
       "\\item[FLAG\\textbackslash{}\\_OWN\\textbackslash{}\\_CAR] 0\n",
       "\\item[FLAG\\textbackslash{}\\_OWN\\textbackslash{}\\_REALTY] 0\n",
       "\\item[CNT\\textbackslash{}\\_CHILDREN] 0\n",
       "\\item[AMT\\textbackslash{}\\_INCOME\\textbackslash{}\\_TOTAL] 0\n",
       "\\item[AMT\\textbackslash{}\\_CREDIT] 0\n",
       "\\item[AMT\\textbackslash{}\\_ANNUITY] 12\n",
       "\\item[AMT\\textbackslash{}\\_GOODS\\textbackslash{}\\_PRICE] 278\n",
       "\\item[NAME\\textbackslash{}\\_TYPE\\textbackslash{}\\_SUITE] 0\n",
       "\\item[NAME\\textbackslash{}\\_INCOME\\textbackslash{}\\_TYPE] 0\n",
       "\\item[NAME\\textbackslash{}\\_EDUCATION\\textbackslash{}\\_TYPE] 0\n",
       "\\item[NAME\\textbackslash{}\\_FAMILY\\textbackslash{}\\_STATUS] 0\n",
       "\\item[NAME\\textbackslash{}\\_HOUSING\\textbackslash{}\\_TYPE] 0\n",
       "\\item[REGION\\textbackslash{}\\_POPULATION\\textbackslash{}\\_RELATIVE] 0\n",
       "\\item[DAYS\\textbackslash{}\\_BIRTH] 0\n",
       "\\item[DAYS\\textbackslash{}\\_EMPLOYED] 0\n",
       "\\item[DAYS\\textbackslash{}\\_REGISTRATION] 0\n",
       "\\item[DAYS\\textbackslash{}\\_ID\\textbackslash{}\\_PUBLISH] 0\n",
       "\\item[OWN\\textbackslash{}\\_CAR\\textbackslash{}\\_AGE] 202929\n",
       "\\item[FLAG\\textbackslash{}\\_MOBIL] 0\n",
       "\\item[FLAG\\textbackslash{}\\_EMP\\textbackslash{}\\_PHONE] 0\n",
       "\\item[FLAG\\textbackslash{}\\_WORK\\textbackslash{}\\_PHONE] 0\n",
       "\\item[FLAG\\textbackslash{}\\_CONT\\textbackslash{}\\_MOBILE] 0\n",
       "\\item[FLAG\\textbackslash{}\\_PHONE] 0\n",
       "\\item[FLAG\\textbackslash{}\\_EMAIL] 0\n",
       "\\item[OCCUPATION\\textbackslash{}\\_TYPE] 0\n",
       "\\item[CNT\\textbackslash{}\\_FAM\\textbackslash{}\\_MEMBERS] 2\n",
       "\\item[REGION\\textbackslash{}\\_RATING\\textbackslash{}\\_CLIENT] 0\n",
       "\\item[REGION\\textbackslash{}\\_RATING\\textbackslash{}\\_CLIENT\\textbackslash{}\\_W\\textbackslash{}\\_CITY] 0\n",
       "\\item[WEEKDAY\\textbackslash{}\\_APPR\\textbackslash{}\\_PROCESS\\textbackslash{}\\_START] 0\n",
       "\\item[HOUR\\textbackslash{}\\_APPR\\textbackslash{}\\_PROCESS\\textbackslash{}\\_START] 0\n",
       "\\item[REG\\textbackslash{}\\_REGION\\textbackslash{}\\_NOT\\textbackslash{}\\_LIVE\\textbackslash{}\\_REGION] 0\n",
       "\\item[REG\\textbackslash{}\\_REGION\\textbackslash{}\\_NOT\\textbackslash{}\\_WORK\\textbackslash{}\\_REGION] 0\n",
       "\\item[LIVE\\textbackslash{}\\_REGION\\textbackslash{}\\_NOT\\textbackslash{}\\_WORK\\textbackslash{}\\_REGION] 0\n",
       "\\item[REG\\textbackslash{}\\_CITY\\textbackslash{}\\_NOT\\textbackslash{}\\_LIVE\\textbackslash{}\\_CITY] 0\n",
       "\\item[REG\\textbackslash{}\\_CITY\\textbackslash{}\\_NOT\\textbackslash{}\\_WORK\\textbackslash{}\\_CITY] 0\n",
       "\\item[LIVE\\textbackslash{}\\_CITY\\textbackslash{}\\_NOT\\textbackslash{}\\_WORK\\textbackslash{}\\_CITY] 0\n",
       "\\item[ORGANIZATION\\textbackslash{}\\_TYPE] 0\n",
       "\\item[EXT\\textbackslash{}\\_SOURCE\\textbackslash{}\\_1] 173378\n",
       "\\item[EXT\\textbackslash{}\\_SOURCE\\textbackslash{}\\_2] 660\n",
       "\\item[EXT\\textbackslash{}\\_SOURCE\\textbackslash{}\\_3] 60965\n",
       "\\item[APARTMENTS\\textbackslash{}\\_AVG] 156061\n",
       "\\item[BASEMENTAREA\\textbackslash{}\\_AVG] 179943\n",
       "\\item[YEARS\\textbackslash{}\\_BEGINEXPLUATATION\\textbackslash{}\\_AVG] 150007\n",
       "\\item[YEARS\\textbackslash{}\\_BUILD\\textbackslash{}\\_AVG] 204488\n",
       "\\item[COMMONAREA\\textbackslash{}\\_AVG] 214865\n",
       "\\item[ELEVATORS\\textbackslash{}\\_AVG] 163891\n",
       "\\item[ENTRANCES\\textbackslash{}\\_AVG] 154828\n",
       "\\item[FLOORSMAX\\textbackslash{}\\_AVG] 153020\n",
       "\\item[FLOORSMIN\\textbackslash{}\\_AVG] 208642\n",
       "\\item[LANDAREA\\textbackslash{}\\_AVG] 182590\n",
       "\\item[LIVINGAPARTMENTS\\textbackslash{}\\_AVG] 210199\n",
       "\\item[LIVINGAREA\\textbackslash{}\\_AVG] 154350\n",
       "\\item[NONLIVINGAPARTMENTS\\textbackslash{}\\_AVG] 213514\n",
       "\\item[NONLIVINGAREA\\textbackslash{}\\_AVG] 169682\n",
       "\\item[APARTMENTS\\textbackslash{}\\_MODE] 156061\n",
       "\\item[BASEMENTAREA\\textbackslash{}\\_MODE] 179943\n",
       "\\item[YEARS\\textbackslash{}\\_BEGINEXPLUATATION\\textbackslash{}\\_MODE] 150007\n",
       "\\item[YEARS\\textbackslash{}\\_BUILD\\textbackslash{}\\_MODE] 204488\n",
       "\\item[COMMONAREA\\textbackslash{}\\_MODE] 214865\n",
       "\\item[ELEVATORS\\textbackslash{}\\_MODE] 163891\n",
       "\\item[ENTRANCES\\textbackslash{}\\_MODE] 154828\n",
       "\\item[FLOORSMAX\\textbackslash{}\\_MODE] 153020\n",
       "\\item[FLOORSMIN\\textbackslash{}\\_MODE] 208642\n",
       "\\item[LANDAREA\\textbackslash{}\\_MODE] 182590\n",
       "\\item[LIVINGAPARTMENTS\\textbackslash{}\\_MODE] 210199\n",
       "\\item[LIVINGAREA\\textbackslash{}\\_MODE] 154350\n",
       "\\item[NONLIVINGAPARTMENTS\\textbackslash{}\\_MODE] 213514\n",
       "\\item[NONLIVINGAREA\\textbackslash{}\\_MODE] 169682\n",
       "\\item[APARTMENTS\\textbackslash{}\\_MEDI] 156061\n",
       "\\item[BASEMENTAREA\\textbackslash{}\\_MEDI] 179943\n",
       "\\item[YEARS\\textbackslash{}\\_BEGINEXPLUATATION\\textbackslash{}\\_MEDI] 150007\n",
       "\\item[YEARS\\textbackslash{}\\_BUILD\\textbackslash{}\\_MEDI] 204488\n",
       "\\item[COMMONAREA\\textbackslash{}\\_MEDI] 214865\n",
       "\\item[ELEVATORS\\textbackslash{}\\_MEDI] 163891\n",
       "\\item[ENTRANCES\\textbackslash{}\\_MEDI] 154828\n",
       "\\item[FLOORSMAX\\textbackslash{}\\_MEDI] 153020\n",
       "\\item[FLOORSMIN\\textbackslash{}\\_MEDI] 208642\n",
       "\\item[LANDAREA\\textbackslash{}\\_MEDI] 182590\n",
       "\\item[LIVINGAPARTMENTS\\textbackslash{}\\_MEDI] 210199\n",
       "\\item[LIVINGAREA\\textbackslash{}\\_MEDI] 154350\n",
       "\\item[NONLIVINGAPARTMENTS\\textbackslash{}\\_MEDI] 213514\n",
       "\\item[NONLIVINGAREA\\textbackslash{}\\_MEDI] 169682\n",
       "\\item[FONDKAPREMONT\\textbackslash{}\\_MODE] 0\n",
       "\\item[HOUSETYPE\\textbackslash{}\\_MODE] 0\n",
       "\\item[TOTALAREA\\textbackslash{}\\_MODE] 148431\n",
       "\\item[WALLSMATERIAL\\textbackslash{}\\_MODE] 0\n",
       "\\item[EMERGENCYSTATE\\textbackslash{}\\_MODE] 0\n",
       "\\item[OBS\\textbackslash{}\\_30\\textbackslash{}\\_CNT\\textbackslash{}\\_SOCIAL\\textbackslash{}\\_CIRCLE] 1021\n",
       "\\item[DEF\\textbackslash{}\\_30\\textbackslash{}\\_CNT\\textbackslash{}\\_SOCIAL\\textbackslash{}\\_CIRCLE] 1021\n",
       "\\item[OBS\\textbackslash{}\\_60\\textbackslash{}\\_CNT\\textbackslash{}\\_SOCIAL\\textbackslash{}\\_CIRCLE] 1021\n",
       "\\item[DEF\\textbackslash{}\\_60\\textbackslash{}\\_CNT\\textbackslash{}\\_SOCIAL\\textbackslash{}\\_CIRCLE] 1021\n",
       "\\item[DAYS\\textbackslash{}\\_LAST\\textbackslash{}\\_PHONE\\textbackslash{}\\_CHANGE] 1\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_2] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_3] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_4] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_5] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_6] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_7] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_8] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_9] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_10] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_11] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_12] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_13] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_14] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_15] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_16] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_17] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_18] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_19] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_20] 0\n",
       "\\item[FLAG\\textbackslash{}\\_DOCUMENT\\textbackslash{}\\_21] 0\n",
       "\\item[AMT\\textbackslash{}\\_REQ\\textbackslash{}\\_CREDIT\\textbackslash{}\\_BUREAU\\textbackslash{}\\_HOUR] 41519\n",
       "\\item[AMT\\textbackslash{}\\_REQ\\textbackslash{}\\_CREDIT\\textbackslash{}\\_BUREAU\\textbackslash{}\\_DAY] 41519\n",
       "\\item[AMT\\textbackslash{}\\_REQ\\textbackslash{}\\_CREDIT\\textbackslash{}\\_BUREAU\\textbackslash{}\\_WEEK] 41519\n",
       "\\item[AMT\\textbackslash{}\\_REQ\\textbackslash{}\\_CREDIT\\textbackslash{}\\_BUREAU\\textbackslash{}\\_MON] 41519\n",
       "\\item[AMT\\textbackslash{}\\_REQ\\textbackslash{}\\_CREDIT\\textbackslash{}\\_BUREAU\\textbackslash{}\\_QRT] 41519\n",
       "\\item[AMT\\textbackslash{}\\_REQ\\textbackslash{}\\_CREDIT\\textbackslash{}\\_BUREAU\\textbackslash{}\\_YEAR] 41519\n",
       "\\end{description*}\n"
      ],
      "text/markdown": [
       "SK_ID_CURR\n",
       ":   0TARGET\n",
       ":   0NAME_CONTRACT_TYPE\n",
       ":   0CODE_GENDER\n",
       ":   0FLAG_OWN_CAR\n",
       ":   0FLAG_OWN_REALTY\n",
       ":   0CNT_CHILDREN\n",
       ":   0AMT_INCOME_TOTAL\n",
       ":   0AMT_CREDIT\n",
       ":   0AMT_ANNUITY\n",
       ":   12AMT_GOODS_PRICE\n",
       ":   278NAME_TYPE_SUITE\n",
       ":   0NAME_INCOME_TYPE\n",
       ":   0NAME_EDUCATION_TYPE\n",
       ":   0NAME_FAMILY_STATUS\n",
       ":   0NAME_HOUSING_TYPE\n",
       ":   0REGION_POPULATION_RELATIVE\n",
       ":   0DAYS_BIRTH\n",
       ":   0DAYS_EMPLOYED\n",
       ":   0DAYS_REGISTRATION\n",
       ":   0DAYS_ID_PUBLISH\n",
       ":   0OWN_CAR_AGE\n",
       ":   202929FLAG_MOBIL\n",
       ":   0FLAG_EMP_PHONE\n",
       ":   0FLAG_WORK_PHONE\n",
       ":   0FLAG_CONT_MOBILE\n",
       ":   0FLAG_PHONE\n",
       ":   0FLAG_EMAIL\n",
       ":   0OCCUPATION_TYPE\n",
       ":   0CNT_FAM_MEMBERS\n",
       ":   2REGION_RATING_CLIENT\n",
       ":   0REGION_RATING_CLIENT_W_CITY\n",
       ":   0WEEKDAY_APPR_PROCESS_START\n",
       ":   0HOUR_APPR_PROCESS_START\n",
       ":   0REG_REGION_NOT_LIVE_REGION\n",
       ":   0REG_REGION_NOT_WORK_REGION\n",
       ":   0LIVE_REGION_NOT_WORK_REGION\n",
       ":   0REG_CITY_NOT_LIVE_CITY\n",
       ":   0REG_CITY_NOT_WORK_CITY\n",
       ":   0LIVE_CITY_NOT_WORK_CITY\n",
       ":   0ORGANIZATION_TYPE\n",
       ":   0EXT_SOURCE_1\n",
       ":   173378EXT_SOURCE_2\n",
       ":   660EXT_SOURCE_3\n",
       ":   60965APARTMENTS_AVG\n",
       ":   156061BASEMENTAREA_AVG\n",
       ":   179943YEARS_BEGINEXPLUATATION_AVG\n",
       ":   150007YEARS_BUILD_AVG\n",
       ":   204488COMMONAREA_AVG\n",
       ":   214865ELEVATORS_AVG\n",
       ":   163891ENTRANCES_AVG\n",
       ":   154828FLOORSMAX_AVG\n",
       ":   153020FLOORSMIN_AVG\n",
       ":   208642LANDAREA_AVG\n",
       ":   182590LIVINGAPARTMENTS_AVG\n",
       ":   210199LIVINGAREA_AVG\n",
       ":   154350NONLIVINGAPARTMENTS_AVG\n",
       ":   213514NONLIVINGAREA_AVG\n",
       ":   169682APARTMENTS_MODE\n",
       ":   156061BASEMENTAREA_MODE\n",
       ":   179943YEARS_BEGINEXPLUATATION_MODE\n",
       ":   150007YEARS_BUILD_MODE\n",
       ":   204488COMMONAREA_MODE\n",
       ":   214865ELEVATORS_MODE\n",
       ":   163891ENTRANCES_MODE\n",
       ":   154828FLOORSMAX_MODE\n",
       ":   153020FLOORSMIN_MODE\n",
       ":   208642LANDAREA_MODE\n",
       ":   182590LIVINGAPARTMENTS_MODE\n",
       ":   210199LIVINGAREA_MODE\n",
       ":   154350NONLIVINGAPARTMENTS_MODE\n",
       ":   213514NONLIVINGAREA_MODE\n",
       ":   169682APARTMENTS_MEDI\n",
       ":   156061BASEMENTAREA_MEDI\n",
       ":   179943YEARS_BEGINEXPLUATATION_MEDI\n",
       ":   150007YEARS_BUILD_MEDI\n",
       ":   204488COMMONAREA_MEDI\n",
       ":   214865ELEVATORS_MEDI\n",
       ":   163891ENTRANCES_MEDI\n",
       ":   154828FLOORSMAX_MEDI\n",
       ":   153020FLOORSMIN_MEDI\n",
       ":   208642LANDAREA_MEDI\n",
       ":   182590LIVINGAPARTMENTS_MEDI\n",
       ":   210199LIVINGAREA_MEDI\n",
       ":   154350NONLIVINGAPARTMENTS_MEDI\n",
       ":   213514NONLIVINGAREA_MEDI\n",
       ":   169682FONDKAPREMONT_MODE\n",
       ":   0HOUSETYPE_MODE\n",
       ":   0TOTALAREA_MODE\n",
       ":   148431WALLSMATERIAL_MODE\n",
       ":   0EMERGENCYSTATE_MODE\n",
       ":   0OBS_30_CNT_SOCIAL_CIRCLE\n",
       ":   1021DEF_30_CNT_SOCIAL_CIRCLE\n",
       ":   1021OBS_60_CNT_SOCIAL_CIRCLE\n",
       ":   1021DEF_60_CNT_SOCIAL_CIRCLE\n",
       ":   1021DAYS_LAST_PHONE_CHANGE\n",
       ":   1FLAG_DOCUMENT_2\n",
       ":   0FLAG_DOCUMENT_3\n",
       ":   0FLAG_DOCUMENT_4\n",
       ":   0FLAG_DOCUMENT_5\n",
       ":   0FLAG_DOCUMENT_6\n",
       ":   0FLAG_DOCUMENT_7\n",
       ":   0FLAG_DOCUMENT_8\n",
       ":   0FLAG_DOCUMENT_9\n",
       ":   0FLAG_DOCUMENT_10\n",
       ":   0FLAG_DOCUMENT_11\n",
       ":   0FLAG_DOCUMENT_12\n",
       ":   0FLAG_DOCUMENT_13\n",
       ":   0FLAG_DOCUMENT_14\n",
       ":   0FLAG_DOCUMENT_15\n",
       ":   0FLAG_DOCUMENT_16\n",
       ":   0FLAG_DOCUMENT_17\n",
       ":   0FLAG_DOCUMENT_18\n",
       ":   0FLAG_DOCUMENT_19\n",
       ":   0FLAG_DOCUMENT_20\n",
       ":   0FLAG_DOCUMENT_21\n",
       ":   0AMT_REQ_CREDIT_BUREAU_HOUR\n",
       ":   41519AMT_REQ_CREDIT_BUREAU_DAY\n",
       ":   41519AMT_REQ_CREDIT_BUREAU_WEEK\n",
       ":   41519AMT_REQ_CREDIT_BUREAU_MON\n",
       ":   41519AMT_REQ_CREDIT_BUREAU_QRT\n",
       ":   41519AMT_REQ_CREDIT_BUREAU_YEAR\n",
       ":   41519\n",
       "\n"
      ],
      "text/plain": [
       "                  SK_ID_CURR                       TARGET \n",
       "                           0                            0 \n",
       "          NAME_CONTRACT_TYPE                  CODE_GENDER \n",
       "                           0                            0 \n",
       "                FLAG_OWN_CAR              FLAG_OWN_REALTY \n",
       "                           0                            0 \n",
       "                CNT_CHILDREN             AMT_INCOME_TOTAL \n",
       "                           0                            0 \n",
       "                  AMT_CREDIT                  AMT_ANNUITY \n",
       "                           0                           12 \n",
       "             AMT_GOODS_PRICE              NAME_TYPE_SUITE \n",
       "                         278                            0 \n",
       "            NAME_INCOME_TYPE          NAME_EDUCATION_TYPE \n",
       "                           0                            0 \n",
       "          NAME_FAMILY_STATUS            NAME_HOUSING_TYPE \n",
       "                           0                            0 \n",
       "  REGION_POPULATION_RELATIVE                   DAYS_BIRTH \n",
       "                           0                            0 \n",
       "               DAYS_EMPLOYED            DAYS_REGISTRATION \n",
       "                           0                            0 \n",
       "             DAYS_ID_PUBLISH                  OWN_CAR_AGE \n",
       "                           0                       202929 \n",
       "                  FLAG_MOBIL               FLAG_EMP_PHONE \n",
       "                           0                            0 \n",
       "             FLAG_WORK_PHONE             FLAG_CONT_MOBILE \n",
       "                           0                            0 \n",
       "                  FLAG_PHONE                   FLAG_EMAIL \n",
       "                           0                            0 \n",
       "             OCCUPATION_TYPE              CNT_FAM_MEMBERS \n",
       "                           0                            2 \n",
       "        REGION_RATING_CLIENT  REGION_RATING_CLIENT_W_CITY \n",
       "                           0                            0 \n",
       "  WEEKDAY_APPR_PROCESS_START      HOUR_APPR_PROCESS_START \n",
       "                           0                            0 \n",
       "  REG_REGION_NOT_LIVE_REGION   REG_REGION_NOT_WORK_REGION \n",
       "                           0                            0 \n",
       " LIVE_REGION_NOT_WORK_REGION       REG_CITY_NOT_LIVE_CITY \n",
       "                           0                            0 \n",
       "      REG_CITY_NOT_WORK_CITY      LIVE_CITY_NOT_WORK_CITY \n",
       "                           0                            0 \n",
       "           ORGANIZATION_TYPE                 EXT_SOURCE_1 \n",
       "                           0                       173378 \n",
       "                EXT_SOURCE_2                 EXT_SOURCE_3 \n",
       "                         660                        60965 \n",
       "              APARTMENTS_AVG             BASEMENTAREA_AVG \n",
       "                      156061                       179943 \n",
       " YEARS_BEGINEXPLUATATION_AVG              YEARS_BUILD_AVG \n",
       "                      150007                       204488 \n",
       "              COMMONAREA_AVG                ELEVATORS_AVG \n",
       "                      214865                       163891 \n",
       "               ENTRANCES_AVG                FLOORSMAX_AVG \n",
       "                      154828                       153020 \n",
       "               FLOORSMIN_AVG                 LANDAREA_AVG \n",
       "                      208642                       182590 \n",
       "        LIVINGAPARTMENTS_AVG               LIVINGAREA_AVG \n",
       "                      210199                       154350 \n",
       "     NONLIVINGAPARTMENTS_AVG            NONLIVINGAREA_AVG \n",
       "                      213514                       169682 \n",
       "             APARTMENTS_MODE            BASEMENTAREA_MODE \n",
       "                      156061                       179943 \n",
       "YEARS_BEGINEXPLUATATION_MODE             YEARS_BUILD_MODE \n",
       "                      150007                       204488 \n",
       "             COMMONAREA_MODE               ELEVATORS_MODE \n",
       "                      214865                       163891 \n",
       "              ENTRANCES_MODE               FLOORSMAX_MODE \n",
       "                      154828                       153020 \n",
       "              FLOORSMIN_MODE                LANDAREA_MODE \n",
       "                      208642                       182590 \n",
       "       LIVINGAPARTMENTS_MODE              LIVINGAREA_MODE \n",
       "                      210199                       154350 \n",
       "    NONLIVINGAPARTMENTS_MODE           NONLIVINGAREA_MODE \n",
       "                      213514                       169682 \n",
       "             APARTMENTS_MEDI            BASEMENTAREA_MEDI \n",
       "                      156061                       179943 \n",
       "YEARS_BEGINEXPLUATATION_MEDI             YEARS_BUILD_MEDI \n",
       "                      150007                       204488 \n",
       "             COMMONAREA_MEDI               ELEVATORS_MEDI \n",
       "                      214865                       163891 \n",
       "              ENTRANCES_MEDI               FLOORSMAX_MEDI \n",
       "                      154828                       153020 \n",
       "              FLOORSMIN_MEDI                LANDAREA_MEDI \n",
       "                      208642                       182590 \n",
       "       LIVINGAPARTMENTS_MEDI              LIVINGAREA_MEDI \n",
       "                      210199                       154350 \n",
       "    NONLIVINGAPARTMENTS_MEDI           NONLIVINGAREA_MEDI \n",
       "                      213514                       169682 \n",
       "          FONDKAPREMONT_MODE               HOUSETYPE_MODE \n",
       "                           0                            0 \n",
       "              TOTALAREA_MODE           WALLSMATERIAL_MODE \n",
       "                      148431                            0 \n",
       "         EMERGENCYSTATE_MODE     OBS_30_CNT_SOCIAL_CIRCLE \n",
       "                           0                         1021 \n",
       "    DEF_30_CNT_SOCIAL_CIRCLE     OBS_60_CNT_SOCIAL_CIRCLE \n",
       "                        1021                         1021 \n",
       "    DEF_60_CNT_SOCIAL_CIRCLE       DAYS_LAST_PHONE_CHANGE \n",
       "                        1021                            1 \n",
       "             FLAG_DOCUMENT_2              FLAG_DOCUMENT_3 \n",
       "                           0                            0 \n",
       "             FLAG_DOCUMENT_4              FLAG_DOCUMENT_5 \n",
       "                           0                            0 \n",
       "             FLAG_DOCUMENT_6              FLAG_DOCUMENT_7 \n",
       "                           0                            0 \n",
       "             FLAG_DOCUMENT_8              FLAG_DOCUMENT_9 \n",
       "                           0                            0 \n",
       "            FLAG_DOCUMENT_10             FLAG_DOCUMENT_11 \n",
       "                           0                            0 \n",
       "            FLAG_DOCUMENT_12             FLAG_DOCUMENT_13 \n",
       "                           0                            0 \n",
       "            FLAG_DOCUMENT_14             FLAG_DOCUMENT_15 \n",
       "                           0                            0 \n",
       "            FLAG_DOCUMENT_16             FLAG_DOCUMENT_17 \n",
       "                           0                            0 \n",
       "            FLAG_DOCUMENT_18             FLAG_DOCUMENT_19 \n",
       "                           0                            0 \n",
       "            FLAG_DOCUMENT_20             FLAG_DOCUMENT_21 \n",
       "                           0                            0 \n",
       "  AMT_REQ_CREDIT_BUREAU_HOUR    AMT_REQ_CREDIT_BUREAU_DAY \n",
       "                       41519                        41519 \n",
       "  AMT_REQ_CREDIT_BUREAU_WEEK    AMT_REQ_CREDIT_BUREAU_MON \n",
       "                       41519                        41519 \n",
       "   AMT_REQ_CREDIT_BUREAU_QRT   AMT_REQ_CREDIT_BUREAU_YEAR \n",
       "                       41519                        41519 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#finding sum of null values in every column\n",
    "colSums(is.na(curr_data))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.0.5"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 64.054521,
   "end_time": "2022-09-13T05:33:29.352186",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2022-09-13T05:32:25.297665",
   "version": "2.3.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
